### ISSUE TITLE
Carta appears to conflict with gopkg.in/guregu/null.v4

### ISSUE THREAD

**Issue by johnknapp** [jackskj/carta#1]
Carta looks great so far. :-)

But there seems to be a conflict with null.v4.

**Relevant code:**

```
import (
	"gopkg.in/guregu/null.v4"
	"github.com/jackskj/carta"
)

type User struct {
	ID           int            `json:"-"`
	FirstName    null.String    `json:"first_name"`
	LastName     null.String    `json:"last_name"`
	Email        string         `json:"email"`
}
```
**What happens:**

- Non-null first and last names are returned as null.

**Expected result:**

- Non-null values should work as expected while using null.v4 _and_ carta packages in the same app.

**Comment by jackskj** [comment]
Can you try using sql.NullString from database/sql package?
As of now, i have taken into account the following datatypes for loading 

- any primative types
- time.Time
- protobuf Timestamp
- sql.NullX from database/sql package 
More information [here](https://github.com/jackskj/carta#data-types-and-relationships)

Another thing you can do is use pointer as follows 
```
	// If your SQL data can be "null", use pointers or sql.NullX
	AuthorId  *int
	CreatedOn *timestamp.Timestamp // protobuf timestamp
	UpdatedOn *time.Time
	SonsorId  sql.NullInt64
```

**Comment by johnknapp** [comment]
Thank you for the inputs. I've only had a brief moment to test but initial findings show same result using `database/sql sql.NullString`. It seems pointer usage (`Name *string`) in the struct gave expected results.

I will reply again after some proper testing.

**Comment by jackskj** [comment]
Great, but I’d like to hear more about the sql.nullstring issue.
I would expect this to work. 
What driver are you using? Is the sql.nullstring field a pointer?

you can compare your tests with that in my test data 
[here are all the null and not null tests](https://github.com/jackskj/carta/blob/master/testdata/null_sql.go)
and [here are their results](https://github.com/jackskj/carta/blob/6edb0f061064baa8bbb981019c26aaaf18198de0/testdata/mapper.golden#L983)

**Comment by jackskj** [comment]
you can compare your tests with that in test data 
[here are all the null and not null tests](https://github.com/jackskj/carta/blob/master/testdata/null_sql.go)
and [here are their results](https://github.com/jackskj/carta/blob/6edb0f061064baa8bbb981019c26aaaf18198de0/testdata/mapper.golden#L983)

**Comment by johnknapp** [comment]
Sorry for the delay on this. It turned out our SQL was at fault. (left vs inner join) We're all good now so I'll close this.
